services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

    command: >
      sh -c "
      while ! nc -z db 5432; do sleep 1; done;
      npx sequelize-cli db:migrate;
      if [ \$(PGPASSWORD=$DB_PASS psql -h $DB_HOST -U $DB_USER -d $DB_NAME -tAc 'SELECT COUNT(*) FROM users;') -eq 0 ]; then
        npx sequelize-cli db:seed:all;
      fi;
      npm start
      "


volumes:
  pgdata:
